// Generated by CoffeeScript 1.4.0
(function() {

  exports.run = function(req, res) {
    if (req.user == null) {
      return res.redirect('/login.html');
    }
    return res.send("hi");
  };

}).call(this);
