// Generated by CoffeeScript 1.4.0
(function() {
  var LocalStrategy, app, db, express, fgapp, fguser, mongoose, passport, site;

  express = require('express');

  passport = require('passport');

  LocalStrategy = require('passport-local').Strategy;

  mongoose = require('mongoose');

  site = require('./site');

  fgapp = require('./fgapp');

  fguser = require('./fguser');

  app = express();

  app.configure(function() {
    app.use(express["static"]('public'));
    app.use(express.cookieParser());
    app.use(express.bodyParser());
    app.use(express.session({
      'secret': "MusawirAliShah"
    }));
    app.use(passport.initialize());
    return app.use(passport.session());
  });

  passport.use(new LocalStrategy(function(username, password, done) {
    console.log("Login request: " + username);
    return done(null, {
      'id': 1
    });
  }));

  passport.serializeUser(function(user, done) {
    return done(null, user.id);
  });

  passport.deserializeUser(function(id, done) {
    return done(null, {
      'username': 'Choo Choo'
    });
  });

  app.get('/', site.index);

  app.get('/app', fgapp.run);

  app.post('/login', passport.authenticate('local', {
    'failureRedirect': '/login.html',
    'successRedirect': '/app',
    failureFlash: true
  }));

  mongoose.connect('mongodb://localhost/fromgenjs');

  db = mongoose.connection;

  db.on('error', console.error.bind(console, 'connection error:'));

  db.on('open', function() {
    var User;
    console.log('Connected to DB, starting server.');
    User = fguser.setup(mongoose);
    User.find(function(err, users) {
      if (err) {
        return console.log(err);
      }
      console.log(users);
      return fguser.createUser({
        username: 'tester',
        password: 'tested',
        email: 'tester@tested.com'
      }, function(err, obj) {
        if (err) {
          return console.log(err);
        }
        return console.log("Saved user");
      });
    });
    return app.listen(3000);
  });

}).call(this);
