// Generated by CoffeeScript 1.4.0
(function() {
  var LocalStrategy, app, express, fgapp, passport, site;

  express = require('express');

  passport = require('passport');

  LocalStrategy = require('passport-local').Strategy;

  site = require('./site');

  fgapp = require('./fgapp');

  app = express();

  app.configure(function() {
    app.use(express["static"]('public'));
    app.use(express.cookieParser());
    app.use(express.bodyParser());
    app.use(express.session({
      'secret': "MusawirAliShah"
    }));
    app.use(passport.initialize());
    return app.use(passport.session());
  });

  passport.use(new LocalStrategy(function(username, password, done) {
    console.log("Login request: " + username);
    return done(null, {
      'id': 1
    });
  }));

  passport.serializeUser(function(user, done) {
    return done(null, user.id);
  });

  passport.deserializeUser(function(id, done) {
    return done(null, {
      'username': 'Choo Choo'
    });
  });

  app.get('/', site.index);

  app.get('/app', fgapp.run);

  app.post('/login', passport.authenticate('local', {
    'failureRedirect': '/login.html',
    'successRedirect': '/app',
    failureFlash: true
  }));

  app.listen(3000);

}).call(this);
